=== fmogollon13/wmmanner/wmmanner/MapaTransaciones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- editado con XMLSpy v2014 (x64) (http://www.altova.com) por WM (WM) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:simpleType name="operationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Registrar"/>
			<xs:enumeration value="Obtener"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="destinyType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ConectorDB"/>
			<xs:enumeration value="ConectorFS"/>
			<xs:enumeration value="ConectorWSJSon"/>
			<xs:enumeration value="ConectorWSObjeto"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="providerType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Ninguno"/>
			<xs:enumeration value="Access"/>
			<xs:enumeration value="Odbc"/>
			<xs:enumeration value="OleDb"/>
			<xs:enumeration value="Oracle"/>
			<xs:enumeration value="Sql"/>
			<xs:enumeration value="SqlCe"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="transacciones">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="proveedor" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tipodestino" type="destinyType"/>
							<xs:element name="TipoProveedor" type="providerType" default="Ninguno"/>
							<xs:element name="CadenaConexion" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="id" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="transaccion" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="destino" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="conexion" type="xs:string"/>
										<xs:element name="tiempoespera" type="xs:integer"/>
										<xs:element name="reintentos" type="xs:integer"/>
										<xs:element name="tiemporeintento" type="xs:integer"/>
										<xs:element name="esobjeto" type="xs:boolean"/>
										<xs:element name="persiste" type="xs:boolean"/>
										<xs:element name="usuario" type="xs:string" minOccurs="0"/>
										<xs:element name="clave" type="xs:string" minOccurs="0"/>
										<xs:element name="dominio" type="xs:string" nillable="false" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="codigo" type="xs:integer" use="required"/>
						<xs:attribute name="operacion" type="operationType" use="required"/>
						<xs:attribute name="Evento" type="xs:short" default="0"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== fmogollon13/wmmanner/wmmanner/MapaTransaciones.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  <auto-generated>
    Este código fue generado por OurCode 1.0.0.1

    Código escrito por Martin Daza
    Fecha: 21-ene-2014 08:48

    Los cambios en este archivo podrían causar un comportamiento incorrecto
    y se perderán si se vuelve a generar el código.
  </auto-generated>
-->
<transacciones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:./MapaTransaciones.xsd">
  <proveedor id="ActivosFijos">
    <tipodestino>ConectorDB</tipodestino>
    <TipoProveedor>Sql</TipoProveedor>
    <CadenaConexion>Data Source=192.168.0.25\SQLWIN_SRV01;Initial Catalog=dlp_WMActivosFijos;User Id=Usr_dlp_WMActivosFijos;Password=Pas_dlp_WMActivosFijos</CadenaConexion>
  </proveedor>
  <!-- ObtenerActivo -->
  <transaccion codigo="5" operacion="Obtener" Evento="1">
    <destino>
      <conexion>ActivosFijos</conexion>
      <tiempoespera>60</tiempoespera>
      <reintentos>1</reintentos>
      <tiemporeintento>10</tiemporeintento>
      <esobjeto>true</esobjeto>
      <persiste>true</persiste>
    </destino>
  </transaccion>
  <!-- ObtenerFechaHora -->
  <transaccion codigo="1" operacion="Obtener" Evento="1">
    <destino>
      <conexion>ActivosFijos</conexion>
      <tiempoespera>60</tiempoespera>
      <reintentos>1</reintentos>
      <tiemporeintento>10</tiemporeintento>
      <esobjeto>true</esobjeto>
      <persiste>true</persiste>
    </destino>
  </transaccion>
  <!-- ObtenerLista -->
  <transaccion codigo="7" operacion="Obtener" Evento="1">
    <destino>
      <conexion>ActivosFijos</conexion>
      <tiempoespera>60</tiempoespera>
      <reintentos>1</reintentos>
      <tiemporeintento>10</tiemporeintento>
      <esobjeto>true</esobjeto>
      <persiste>true</persiste>
    </destino>
  </transaccion>
  <!-- ObtenerListaEditable -->
  <transaccion codigo="6" operacion="Obtener" Evento="1">
    <destino>
      <conexion>ActivosFijos</conexion>
      <tiempoespera>60</tiempoespera>
      <reintentos>1</reintentos>
      <tiemporeintento>10</tiemporeintento>
      <esobjeto>true</esobjeto>
      <persiste>true</persiste>
    </destino>
  </transaccion>
  <!-- ObtenerLogin -->
  <transaccion codigo="2" operacion="Obtener" Evento="1">
    <destino>
      <conexion>ActivosFijos</conexion>
      <tiempoespera>60</tiempoespera>
      <reintentos>1</reintentos>
      <tiemporeintento>10</tiemporeintento>
      <esobjeto>true</esobjeto>
      <persiste>true</persiste>
    </destino>
  </transaccion>
  <!-- ObtenerRolFuncion -->
  <transaccion codigo="4" operacion="Obtener" Evento="1">
    <destino>
      <conexion>ActivosFijos</conexion>
      <tiempoespera>60</tiempoespera>
      <reintentos>1</reintentos>
      <tiemporeintento>10</tiemporeintento>
      <esobjeto>true</esobjeto>
      <persiste>true</persiste>
    </destino>
  </transaccion>
  <!-- ObtenerUsuario -->
  <transaccion codigo="11" operacion="Obtener" Evento="1">
    <destino>
      <conexion>ActivosFijos</conexion>
      <tiempoespera>60</tiempoespera>
      <reintentos>1</reintentos>
      <tiemporeintento>10</tiemporeintento>
      <esobjeto>true</esobjeto>
      <persiste>true</persiste>
    </destino>
  </transaccion>
  <!-- ObtenerUsuarioRol -->
  <transaccion codigo="3" operacion="Obtener" Evento="1">
    <destino>
      <conexion>ActivosFijos</conexion>
      <tiempoespera>60</tiempoespera>
      <reintentos>1</reintentos>
      <tiemporeintento>10</tiemporeintento>
      <esobjeto>true</esobjeto>
      <persiste>true</persiste>
    </destino>
  </transaccion>
  <!-- RegistrarActivoEjecutado -->
  <transaccion codigo="8" operacion="Registrar" Evento="1">
    <destino>
      <conexion>ActivosFijos</conexion>
      <tiempoespera>60</tiempoespera>
      <reintentos>1</reintentos>
      <tiemporeintento>10</tiemporeintento>
      <esobjeto>true</esobjeto>
      <persiste>true</persiste>
    </destino>
  </transaccion>
  <!-- RegistrarListaEditableEjecutada -->
  <transaccion codigo="9" operacion="Registrar" Evento="1">
    <destino>
      <conexion>ActivosFijos</conexion>
      <tiempoespera>60</tiempoespera>
      <reintentos>1</reintentos>
      <tiemporeintento>10</tiemporeintento>
      <esobjeto>true</esobjeto>
      <persiste>true</persiste>
    </destino>
  </transaccion>
  <!-- RegistrarLogTransaccionesAct -->
  <transaccion codigo="10" operacion="Registrar" Evento="1">
    <destino>
      <conexion>ActivosFijos</conexion>
      <tiempoespera>60</tiempoespera>
      <reintentos>1</reintentos>
      <tiemporeintento>10</tiemporeintento>
      <esobjeto>true</esobjeto>
      <persiste>true</persiste>
    </destino>
  </transaccion>
</transacciones>
